export const INCREMENT="INCREMENT"
export const DECREMENT="DECREMENT"


//?Comments
export const ADD_COMMENTS="ADD_COMMENTS"
export const DELETE_COMMENTS="DELETE_COMMENTS"
export const GET_POST_COMMENT="GET_POST_COMMENT"

//?loading
export const SHOW_LOADING="SHOW_LOADING"
export const HIDE_LOADING="HIDE_LOADING"

//?ERROR
export const SHOW_ERROR="SHOW_ERROR"
export const CLEAR_ERROR="CLEAR_ERROR"